# Generated by Django 4.1.1 on 2022-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=20)),
                ('job_description', models.CharField(max_length=1000, null=True)),
                ('postmail_place', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('project_name', models.CharField(max_length=50, null=True)),
                ('project_callnumber', models.IntegerField(max_length=13, null=True)),
                ('projectowner_first_name', models.CharField(max_length=50, null=True)),
                ('projectowner_last_name', models.CharField(max_length=50, null=True)),
                ('projectowner_fathers_name', models.CharField(max_length=50, null=True)),
                ('project_sum', models.IntegerField(max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ('Користуавч',),
                'verbose_name_plural': 'Користувачі',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=1000)),
                ('date_start', models.DateTimeField()),
                ('date_stop', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ('Програма',),
                'verbose_name_plural': 'Програми',
            },
        ),
    ]
